language: node_js
node_js:
  - '0.10'
before_script:
  - gem update --system
  - gem install compass
  - npm install -g bower grunt-cli
  - bower install
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - grunt test

notifications:
  email: false
